version: '3'
services:
        web:
                build: "."
                ports:
                        - "3000:3000"
                volumes:
                        - ".:/node_app"
                        - "/node_app/node_modules"
        redis:
                image: "redis:alpine"
